-- Initial schema, matching the JPA entities as they were when Flyway was introduced.
-- Runs on both H2 (local development) and Postgres (Supabase), so keep it portable SQL.

CREATE TABLE app_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Google's `sub` claim; null for email/password accounts
  google_id VARCHAR(255) CONSTRAINT app_users_google_id_key UNIQUE,
  -- Stored lowercase by the application
  email VARCHAR(255) NOT NULL CONSTRAINT app_users_email_key UNIQUE,
  -- PBKDF2 hash; null for Google-only accounts
  password_hash VARCHAR(255),
  name VARCHAR(255),
  picture_url VARCHAR(255),
  role VARCHAR(255) NOT NULL
);

CREATE TABLE dishes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  owner_id BIGINT NOT NULL CONSTRAINT dishes_owner_id_fkey REFERENCES app_users(id)
);

CREATE TABLE daily_sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dish_id BIGINT NOT NULL CONSTRAINT daily_sales_dish_id_fkey REFERENCES dishes(id),
  sale_date DATE NOT NULL,
  quantity_sold INTEGER NOT NULL,
  CONSTRAINT daily_sales_dish_id_sale_date_key UNIQUE (dish_id, sale_date)
);

CREATE TABLE public_holidays (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL CONSTRAINT public_holidays_date_key UNIQUE,
  name VARCHAR(255) NOT NULL
);

-- Postgres does not index foreign keys automatically; these back the owner and history lookups.
CREATE INDEX dishes_owner_id_idx ON dishes(owner_id);
