from __future__ import annotations

import pytest

from ml.model_comparison import load_dish_days
from ml.src.models.inference import (
    FEATURE_SCHEMA_PATH,
    MODEL_PATH,
    load_feature_schema,
    load_model,
    predict_demand,
    validate_features,
)

@pytest.fixture(scope="module")
def production_artifacts():
    """
    Load the locally generated production schema and model once
    for all integration tests in this file.

    Production artifacts are generated by:
        python -m ml.train_production

    They are intentionally not committed to Git.
    """

    if not FEATURE_SCHEMA_PATH.exists():
        pytest.skip(
            "Production feature schema not found. "
            "Run: python -m ml.train_production"
        )

    if not MODEL_PATH.exists():
        pytest.skip(
            "Production model not found. "
            "Run: python -m ml.train_production"
        )

    schema = load_feature_schema()
    model = load_model()

    return schema, model


@pytest.fixture(scope="module")
def long_df():
    _, dataframe = load_dish_days()

    return dataframe


@pytest.fixture(scope="module")
def valid_features(
    production_artifacts,
    long_df,
):
    """
    Construct one valid model-ready feature dictionary from
    a real row in the processed dataset.
    """

    schema, _ = production_artifacts

    row = long_df.iloc[-1]

    return {
        feature: row[feature]
        for feature in schema["feature_order"]
    }

# schema tests
def test_feature_schema_matches_training_data(
    production_artifacts,
    long_df,
):
    schema, _ = production_artifacts

    expected_numeric_features = [
        column
        for column in long_df.columns
        if column not in (
            "DEMAND_DATE",
            "DISH",
            "DEMAND",
        )
    ]

    assert schema["categorical_features"] == [
        "DISH"
    ]

    assert schema["numeric_features"] == (
        expected_numeric_features
    )

    assert schema["feature_order"] == [
        "DISH",
        *expected_numeric_features,
    ]

    assert schema["target"] == "DEMAND"


# validation tests
def test_validate_features_accepts_valid_input(
    production_artifacts,
    valid_features,
):
    """
    A complete feature dictionary should pass validation
    without raising an exception.
    """

    schema, _ = production_artifacts

    validate_features(
        valid_features,
        schema,
    )


def test_validate_features_rejects_missing_feature(
    production_artifacts,
    valid_features,
):
    """
    A missing required feature should raise ValueError.
    """

    schema, _ = production_artifacts

    broken_features = valid_features.copy()

    broken_features.pop(
        "AIR_TEMPERATURE"
    )

    with pytest.raises(
        ValueError,
        match="Missing required features",
    ):
        validate_features(
            broken_features,
            schema,
        )


def test_validate_features_rejects_extra_feature(
    production_artifacts,
    valid_features,
):
    """
    An unexpected feature should raise ValueError.
    """

    schema, _ = production_artifacts

    broken_features = valid_features.copy()

    broken_features[
        "RANDOM_FEATURE"
    ] = 123

    with pytest.raises(
        ValueError,
        match="Unexpected features",
    ):
        validate_features(
            broken_features,
            schema,
        )


# prediction test
def test_predict_demand_returns_float(
    production_artifacts,
    valid_features,
):
    """
    The inference wrapper should return one numeric prediction
    as a Python float.
    """

    schema, model = production_artifacts

    prediction = predict_demand(
        valid_features,
        model,
        schema,
    )

    assert isinstance(
        prediction,
        float,
    )


def test_wrapper_prediction_matches_direct_model_prediction(
    production_artifacts,
    valid_features,
    long_df,
):
    """
    The inference wrapper must produce the same result as
    calling CatBoost directly with the correctly ordered row.

    This verifies that validation and DataFrame reconstruction
    do not alter or misorder model inputs.
    """

    schema, model = production_artifacts

    wrapper_prediction = predict_demand(
        valid_features,
        model,
        schema,
    )

    direct_input = long_df.iloc[[-1]][
        schema["feature_order"]
    ]

    direct_prediction = float(
        model.predict(
            direct_input
        )[0]
    )

    assert wrapper_prediction == pytest.approx(
        direct_prediction,
        abs=1e-12,
    )